# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'luncherUI.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(724, 432)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_15.addWidget(self.label_21)
        self.cageBox = QtWidgets.QLineEdit(Form)
        self.cageBox.setMinimumSize(QtCore.QSize(60, 0))
        self.cageBox.setObjectName("cageBox")
        self.horizontalLayout_15.addWidget(self.cageBox)
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_15.addWidget(self.label_22)
        self.mouseBox = QtWidgets.QLineEdit(Form)
        self.mouseBox.setMaximumSize(QtCore.QSize(40, 16777215))
        self.mouseBox.setObjectName("mouseBox")
        self.horizontalLayout_15.addWidget(self.mouseBox)
        self.checkButton = QtWidgets.QPushButton(Form)
        self.checkButton.setObjectName("checkButton")
        self.horizontalLayout_15.addWidget(self.checkButton)
        self.line_8 = QtWidgets.QFrame(Form)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_15.addWidget(self.line_8)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_15.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_15.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.horizontalLayout_15, 13, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.stepTwo = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.stepTwo.setFont(font)
        self.stepTwo.setObjectName("stepTwo")
        self.gridLayout.addWidget(self.stepTwo, 5, 0, 1, 1)
        self.stepThree = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.stepThree.setFont(font)
        self.stepThree.setObjectName("stepThree")
        self.gridLayout.addWidget(self.stepThree, 9, 0, 1, 1)
        self.stepOne = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.stepOne.setFont(font)
        self.stepOne.setObjectName("stepOne")
        self.gridLayout.addWidget(self.stepOne, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 15, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 8, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 14, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.serialDrop = QtWidgets.QComboBox(Form)
        self.serialDrop.setObjectName("serialDrop")
        self.horizontalLayout.addWidget(self.serialDrop)
        self.serialButton = QtWidgets.QPushButton(Form)
        self.serialButton.setObjectName("serialButton")
        self.horizontalLayout.addWidget(self.serialButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.userText = QtWidgets.QLineEdit(Form)
        self.userText.setObjectName("userText")
        self.horizontalLayout_5.addWidget(self.userText)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.passText = QtWidgets.QLineEdit(Form)
        self.passText.setObjectName("passText")
        self.horizontalLayout_5.addWidget(self.passText)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.dbText = QtWidgets.QLineEdit(Form)
        self.dbText.setObjectName("dbText")
        self.horizontalLayout_5.addWidget(self.dbText)
        self.gridLayout.addLayout(self.horizontalLayout_5, 7, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fileText = QtWidgets.QLineEdit(Form)
        self.fileText.setObjectName("fileText")
        self.horizontalLayout_3.addWidget(self.fileText)
        self.fileButton = QtWidgets.QPushButton(Form)
        self.fileButton.setObjectName("fileButton")
        self.horizontalLayout_3.addWidget(self.fileButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 10, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.ipText = QtWidgets.QLineEdit(Form)
        self.ipText.setObjectName("ipText")
        self.horizontalLayout_4.addWidget(self.ipText)
        self.sqlButton = QtWidgets.QPushButton(Form)
        self.sqlButton.setObjectName("sqlButton")
        self.horizontalLayout_4.addWidget(self.sqlButton)
        self.gridLayout.addLayout(self.horizontalLayout_4, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 12, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(Form)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 11, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.lunchButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lunchButton.sizePolicy().hasHeightForWidth())
        self.lunchButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(16)
        self.lunchButton.setFont(font)
        self.lunchButton.setAutoDefault(True)
        self.lunchButton.setDefault(False)
        self.lunchButton.setObjectName("lunchButton")
        self.gridLayout_2.addWidget(self.lunchButton, 0, 4, 1, 1)
        self.settingsWidget = QtWidgets.QWidget(Form)
        self.settingsWidget.setObjectName("settingsWidget")
        self.gridLayout_2.addWidget(self.settingsWidget, 0, 2, 1, 1)
        self.line_6 = QtWidgets.QFrame(Form)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 0, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Behavior Luncher"))
        self.label_21.setText(_translate("Form", "Cage ID"))
        self.label_22.setText(_translate("Form", "Mouse ID"))
        self.checkButton.setText(_translate("Form", "Check-In"))
        self.label_2.setText(_translate("Form", "Scanner:"))
        self.label_4.setText(_translate("Form", "Choose one or both below (2 alone, 3 alone, or 2 and 3)"))
        self.stepTwo.setText(_translate("Form", "Step 2: Connect to Database"))
        self.stepThree.setText(_translate("Form", "Step 3: Choose File to Save"))
        self.stepOne.setText(_translate("Form", "Step 1: Connect to Serial"))
        self.serialButton.setText(_translate("Form", "Connect"))
        self.label_6.setText(_translate("Form", "User"))
        self.userText.setText(_translate("Form", "dennis"))
        self.label_7.setText(_translate("Form", "Pass"))
        self.passText.setText(_translate("Form", "rh960615"))
        self.label_8.setText(_translate("Form", "Database"))
        self.dbText.setText(_translate("Form", "Salk"))
        self.fileButton.setText(_translate("Form", "Browse"))
        self.label_5.setText(_translate("Form", "ServerAddress"))
        self.ipText.setText(_translate("Form", "ssh.dennisren.com"))
        self.sqlButton.setText(_translate("Form", "Connect"))
        self.label.setText(_translate("Form", "Step 4: Who\'s There?"))
        self.lunchButton.setText(_translate("Form", "Launch"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

