# -*- coding: utf-8 -*-
from serial.tools import list_ports
import fnmatch
import serial
import mysql.connector
import time,sys,json
import csv,os
# Form implementation generated from reading ui file 'luncherUI.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Settings(QtWidgets.QWidget):
    def __init__(self,comPort):
        super().__init__()
        abspath = os.path.abspath(__file__)
        dname = os.path.dirname(abspath)
        os.chdir(dname)
        cwd = os.getcwd()
        print(cwd)
        jsondat = open('settings.json').read()
        self.jsettings=json.loads(jsondat)

        self.setupUi(self)
        self.comPort=comPort
        phaseGroup = QtWidgets.QButtonGroup(self)  # Letter group
        phaseGroup.addButton(self.p1Button)
        phaseGroup.addButton(self.p2Button)

        dispGroup=QtWidgets.QButtonGroup(self)
        dispGroup.addButton(self.d1tBox)
        dispGroup.addButton(self.d1bBox)
        dispGroup.addButton(self.d2tBox)
        dispGroup.addButton(self.d2bBox)
        if self.jsettings['session_default']['position'] == 1:
            self.d1tBox.setChecked(True)
        elif self.jsettings['session_default']['position'] == 2:
            self.d1bBox.setChecked(True)
        elif self.jsettings['session_default']['position'] == 3:
            self.d2tBox.setChecked(True)
        elif self.jsettings['session_default']['position'] == 4:
            self.d2bBox.setChecked(True)

        if self.jsettings['mcu_config']['training_phase']==1:
            self.p1Button.setChecked(True)
            self.p2Button.setChecked(False)
        elif self.jsettings['mcu_config']['training_phase'] == 2:
            self.p2Button.setChecked(True)
            self.p1Button.setChecked(False)
        self.dripBox.setValue(self.jsettings['mcu_config']['drip_delay_time'])
        self.punishBox.setValue(self.jsettings['mcu_config']['punishment_duration'])
        self.delayBox.setValue(self.jsettings['mcu_config']['delay_duration'])
        self.toneBox.setValue(self.jsettings['mcu_config']['tone_duration'])
        self.betweenToneBox.setValue(self.jsettings['mcu_config']['time_between_tones'])
        self.valveBox.setValue(self.jsettings['mcu_config']['valve_open_time'])
        self.lickBox.setValue(self.jsettings['mcu_config']['lickwindow_duration'])
        self.trailBox.setValue(self.jsettings['mcu_config']['trial_number'])
        self.minBox.setValue(self.jsettings['mcu_config']['min_difficulty'])
        self.maxBox.setValue(self.jsettings['mcu_config']['max_difficulty'])

        self.downloadButton.clicked.connect(self.getout)
        self.minBox.valueChanged.connect(self.repairLimit)
        self.maxBox.valueChanged.connect(self.repairLimit)

        self.show()

    def repairLimit(self):
        self.maxBox.setMinimum(self.minBox.value())
        self.minBox.setMaximum(self.maxBox.value())
    def getout(self):
        self.jsettings['mcu_config']['drip_delay_time']         =   self.dripBox.value()
        self.jsettings['mcu_config']['punishment_duration']     =   self.punishBox.value()
        self.jsettings['mcu_config']['delay_duration']          =   self.delayBox.value()
        self.jsettings['mcu_config']['tone_duration']           =   self.toneBox.value()
        self.jsettings['mcu_config']['time_between_tones']      =   self.betweenToneBox.value()
        self.jsettings['mcu_config']['valve_open_time']         =   self.valveBox.value()
        self.jsettings['mcu_config']['lickwindow_duration']     =   self.lickBox.value()
        self.jsettings['mcu_config']['trial_number']            =   self.trailBox.value()
        self.jsettings['mcu_config']['min_difficulty']          =   self.minBox.value()
        self.jsettings['mcu_config']['max_difficulty']          =   self.maxBox.value()
        self.jsettings['mcu_config']['training_phase'] = 1 if self.p1Button.isChecked() and self.p2Button.isChecked() else 2
        self.jsettings['session_default']['position']+=1
        if self.jsettings['session_default']['position'] == 5:
            self.jsettings['session_default']['position']=1


        self.download()
        with open('settings.json', 'w') as outfile:
            json.dump(self.jsettings, outfile)
        self.close()

    def download(self):
        try:
            self.ComPort = serial.Serial(self.comPort)  # open the COM Port
            self.ComPort.baudrate = 21000  # set Baud rate
            self.ComPort.bytesize = 8  # Number of data bits = 8
            self.ComPort.parity = 'N'  # No parity
            self.ComPort.stopbits = 1  # Number of Stop bits = 1
        except Exception as e:
            print(str(e))


    def setupUi(self,Form):
        Form.setObjectName("Form")
        Form.resize(326, 417)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.lickBox = QtWidgets.QDoubleSpinBox(Form)
        self.lickBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.lickBox.setMaximum(5.0)
        self.lickBox.setSingleStep(0.05)
        self.lickBox.setObjectName("lickBox")
        self.horizontalLayout_7.addWidget(self.lickBox)
        self.label_12 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.gridLayout.addLayout(self.horizontalLayout_7, 7, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.delayBox = QtWidgets.QDoubleSpinBox(Form)
        self.delayBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.delayBox.setMaximum(5.0)
        self.delayBox.setSingleStep(0.05)
        self.delayBox.setObjectName("delayBox")
        self.horizontalLayout_6.addWidget(self.delayBox)
        self.label_15 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_6.addWidget(self.label_15)
        self.gridLayout.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.p1Button = QtWidgets.QRadioButton(Form)
        self.p1Button.setObjectName("p1Button")
        self.horizontalLayout.addWidget(self.p1Button)
        self.p2Button = QtWidgets.QRadioButton(Form)
        self.p2Button.setObjectName("p2Button")
        self.horizontalLayout.addWidget(self.p2Button)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.toneBox = QtWidgets.QDoubleSpinBox(Form)
        self.toneBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.toneBox.setMaximum(5.0)
        self.toneBox.setSingleStep(0.05)
        self.toneBox.setObjectName("toneBox")
        self.horizontalLayout_3.addWidget(self.toneBox)
        self.label_14 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.betweenToneBox = QtWidgets.QDoubleSpinBox(Form)
        self.betweenToneBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.betweenToneBox.setMaximum(5.0)
        self.betweenToneBox.setSingleStep(0.05)
        self.betweenToneBox.setObjectName("betweenToneBox")
        self.horizontalLayout_4.addWidget(self.betweenToneBox)
        self.label_13 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.gridLayout.addLayout(self.horizontalLayout_4, 6, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.punishBox = QtWidgets.QDoubleSpinBox(Form)
        self.punishBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.punishBox.setMaximum(5.0)
        self.punishBox.setSingleStep(0.05)
        self.punishBox.setObjectName("punishBox")
        self.horizontalLayout_2.addWidget(self.punishBox)
        self.label_16 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_2.addWidget(self.label_16)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.maxBox = QtWidgets.QSpinBox(Form)
        self.maxBox.setObjectName("maxBox")
        self.horizontalLayout_11.addWidget(self.maxBox)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.minBox = QtWidgets.QSpinBox(Form)
        self.minBox.setObjectName("minBox")
        self.horizontalLayout_9.addWidget(self.minBox)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.gridLayout.addLayout(self.horizontalLayout_10, 11, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.valveBox = QtWidgets.QDoubleSpinBox(Form)
        self.valveBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.valveBox.setMaximum(5.0)
        self.valveBox.setSingleStep(0.05)
        self.valveBox.setObjectName("valveBox")
        self.horizontalLayout_8.addWidget(self.valveBox)
        self.label_11 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.gridLayout.addLayout(self.horizontalLayout_8, 8, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_5.addWidget(self.label_20)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.d1tBox = QtWidgets.QRadioButton(Form)
        self.d1tBox.setObjectName("d1tBox")
        self.gridLayout_3.addWidget(self.d1tBox, 0, 0, 1, 1)
        self.d2tBox = QtWidgets.QRadioButton(Form)
        self.d2tBox.setObjectName("d2tBox")
        self.gridLayout_3.addWidget(self.d2tBox, 0, 1, 1, 1)
        self.d1bBox = QtWidgets.QRadioButton(Form)
        self.d1bBox.setObjectName("d1bBox")
        self.gridLayout_3.addWidget(self.d1bBox, 1, 0, 1, 1)
        self.d2bBox = QtWidgets.QRadioButton(Form)
        self.d2bBox.setObjectName("d2bBox")
        self.gridLayout_3.addWidget(self.d2bBox, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_5, 17, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_13.addWidget(self.label_17)
        self.trailBox = QtWidgets.QSpinBox(Form)
        self.trailBox.setMaximum(200)
        self.trailBox.setSingleStep(5)
        self.trailBox.setObjectName("trailBox")
        self.horizontalLayout_13.addWidget(self.trailBox)
        self.gridLayout.addLayout(self.horizontalLayout_13, 15, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_12.addWidget(self.label_18)
        self.dripBox = QtWidgets.QDoubleSpinBox(Form)
        self.dripBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dripBox.setMaximum(5.0)
        self.dripBox.setSingleStep(0.05)
        self.dripBox.setObjectName("dripBox")
        self.horizontalLayout_12.addWidget(self.dripBox)
        self.label_19 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_12.addWidget(self.label_19)
        self.gridLayout.addLayout(self.horizontalLayout_12, 9, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 16, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 12, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 10, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.downloadButton = QtWidgets.QPushButton(Form)
        self.downloadButton.setObjectName("downloadButton")
        self.gridLayout_2.addWidget(self.downloadButton, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)





    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Lickwindow Duration"))
        self.label_12.setText(_translate("Form", "Seconds"))
        self.label_6.setText(_translate("Form", "Delay Duration"))
        self.label_15.setText(_translate("Form", "Seconds"))
        self.label.setText(_translate("Form", "Training Phase"))
        self.p1Button.setText(_translate("Form", "Phase 1"))
        self.p2Button.setText(_translate("Form", "Phase 2"))
        self.label_3.setText(_translate("Form", "Tone Duration"))
        self.label_14.setText(_translate("Form", "Seconds"))
        self.label_4.setText(_translate("Form", "Time Between Tones"))
        self.label_13.setText(_translate("Form", "Seconds"))
        self.label_2.setText(_translate("Form", "Punishment Duration"))
        self.label_16.setText(_translate("Form", "Seconds"))
        self.label_7.setText(_translate("Form", "Difficulty"))
        self.label_8.setText(_translate("Form", "Max"))
        self.label_9.setText(_translate("Form", "Min"))
        self.label_10.setText(_translate("Form", "Valve Open Time"))
        self.label_11.setText(_translate("Form", "Seconds"))
        self.label_20.setText(_translate("Form", "GUI Position"))
        self.d1tBox.setText(_translate("Form", "Disp1 Top"))
        self.d2tBox.setText(_translate("Form", "Disp2 Top"))
        self.d1bBox.setText(_translate("Form", "Disp1 Bottom"))
        self.d2bBox.setText(_translate("Form", "Disp2 Bottom"))
        self.label_17.setText(_translate("Form", "Trail Number"))
        self.label_18.setText(_translate("Form", "Drip Delay Time"))
        self.label_19.setText(_translate("Form", "Seconds"))
        self.downloadButton.setText(_translate("Form", "Download Settings"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    prep = Settings("COM4")
    app.exec_()
